type GameMapTileConfig = {
  id: string;
  x: number;
  y: number;
  width: number;
  height: number;
  kind: "copperMine" | "town";
  level: number;
  label?: string;
  shape?: string[];
};

const copperMineShapes = {
  topLeftCorner: ["XXX", "XXX", "XX."],
  topRightCorner: ["XXX", "XXX", ".XX"],
  bottomRightCorner: [".XX", "XXX", "XXX"],
  bottomLeftCorner: ["XX.", "XXX", "XXX"],
  topEdge: ["XXX", "XXX", ".X."],
  rightEdge: [".XX", "XXX", ".XX"],
  bottomEdge: [".X.", "XXX", "XXX"],
  leftEdge: ["XX.", "XXX", "XX."],
  middleTile: [".X.", "XXX", ".X."],
} satisfies Record<string, string[]>;

export const seasonTwoColumns = 39;
export const seasonTwoRowsCount = 39;

export const seasonTwoTiles: GameMapTileConfig[] = [
  { id: "s2-r01-c01-copper", x: 1, y: 1, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.topLeftCorner },
  { id: "s2-r01-c02-copper", x: 4, y: 1, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.topEdge },
  { id: "s2-r01-c03-copper", x: 7, y: 1, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.topEdge },
  { id: "s2-r01-c04-copper", x: 10, y: 1, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.topEdge },
  { id: "s2-r01-c05-copper", x: 13, y: 1, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.topEdge },
  { id: "s2-r01-c06-copper", x: 16, y: 1, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.topEdge },
  { id: "s2-r01-c07-copper", x: 19, y: 1, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.topEdge },
  { id: "s2-r01-c08-copper", x: 22, y: 1, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.topEdge },
  { id: "s2-r01-c09-copper", x: 25, y: 1, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.topEdge },
  { id: "s2-r01-c10-copper", x: 28, y: 1, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.topEdge },
  { id: "s2-r01-c11-copper", x: 31, y: 1, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.topEdge },
  { id: "s2-r01-c12-copper", x: 34, y: 1, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.topEdge },
  { id: "s2-r01-c13-copper", x: 37, y: 1, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.topRightCorner },
  { id: "s2-r02-c01-copper", x: 1, y: 4, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.leftEdge },
  { id: "s2-r02-c02-copper", x: 4, y: 4, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r02-c03-copper", x: 7, y: 4, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r02-c04-copper", x: 10, y: 4, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r02-c05-copper", x: 13, y: 4, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r02-c06-copper", x: 16, y: 4, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r02-c07-copper", x: 19, y: 4, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r02-c08-copper", x: 22, y: 4, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r02-c09-copper", x: 25, y: 4, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r02-c10-copper", x: 28, y: 4, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r02-c11-copper", x: 31, y: 4, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r02-c12-copper", x: 34, y: 4, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r02-c13-copper", x: 37, y: 4, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.rightEdge },
  { id: "s2-r03-c01-copper", x: 1, y: 7, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.leftEdge },
  { id: "s2-r03-c02-copper", x: 4, y: 7, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r03-c03-copper", x: 7, y: 7, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r03-c04-copper", x: 10, y: 7, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r03-c05-copper", x: 13, y: 7, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r03-c06-copper", x: 16, y: 7, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r03-c07-copper", x: 19, y: 7, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r03-c08-copper", x: 22, y: 7, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r03-c09-copper", x: 25, y: 7, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r03-c10-copper", x: 28, y: 7, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r03-c11-copper", x: 31, y: 7, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r03-c12-copper", x: 34, y: 7, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r03-c13-copper", x: 37, y: 7, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.rightEdge },
  { id: "s2-r04-c01-copper", x: 1, y: 10, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.leftEdge },
  { id: "s2-r04-c02-copper", x: 4, y: 10, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r04-c03-copper", x: 7, y: 10, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r04-c04-copper", x: 10, y: 10, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r04-c05-copper", x: 13, y: 10, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r04-c06-copper", x: 16, y: 10, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r04-c07-copper", x: 19, y: 10, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r04-c08-copper", x: 22, y: 10, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r04-c09-copper", x: 25, y: 10, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r04-c10-copper", x: 28, y: 10, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r04-c11-copper", x: 31, y: 10, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r04-c12-copper", x: 34, y: 10, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r04-c13-copper", x: 37, y: 10, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.rightEdge },
  { id: "s2-r05-c01-copper", x: 1, y: 13, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.leftEdge },
  { id: "s2-r05-c02-copper", x: 4, y: 13, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r05-c03-copper", x: 7, y: 13, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r05-c04-copper", x: 10, y: 13, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r05-c05-copper", x: 13, y: 13, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r05-c06-copper", x: 16, y: 13, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r05-c07-copper", x: 19, y: 13, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r05-c08-copper", x: 22, y: 13, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r05-c09-copper", x: 25, y: 13, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r05-c10-copper", x: 28, y: 13, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r05-c11-copper", x: 31, y: 13, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r05-c12-copper", x: 34, y: 13, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r05-c13-copper", x: 37, y: 13, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.rightEdge },
  { id: "s2-r06-c01-copper", x: 1, y: 16, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.leftEdge },
  { id: "s2-r06-c02-copper", x: 4, y: 16, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r06-c03-copper", x: 7, y: 16, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r06-c04-copper", x: 10, y: 16, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r06-c05-copper", x: 13, y: 16, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r06-c06-copper", x: 16, y: 16, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r06-c07-copper", x: 19, y: 16, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r06-c08-copper", x: 22, y: 16, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r06-c09-copper", x: 25, y: 16, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r06-c10-copper", x: 28, y: 16, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r06-c11-copper", x: 31, y: 16, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r06-c12-copper", x: 34, y: 16, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r06-c13-copper", x: 37, y: 16, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.rightEdge },
  { id: "s2-r07-c01-copper", x: 1, y: 19, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.leftEdge },
  { id: "s2-r07-c02-copper", x: 4, y: 19, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r07-c03-copper", x: 7, y: 19, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r07-c04-copper", x: 10, y: 19, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r07-c05-copper", x: 13, y: 19, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r07-c06-copper", x: 16, y: 19, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r07-c07-copper", x: 19, y: 19, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r07-c08-copper", x: 22, y: 19, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r07-c09-copper", x: 25, y: 19, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r07-c10-copper", x: 28, y: 19, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r07-c11-copper", x: 31, y: 19, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r07-c12-copper", x: 34, y: 19, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r07-c13-copper", x: 37, y: 19, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.rightEdge },
  { id: "s2-r08-c01-copper", x: 1, y: 22, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.leftEdge },
  { id: "s2-r08-c02-copper", x: 4, y: 22, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r08-c03-copper", x: 7, y: 22, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r08-c04-copper", x: 10, y: 22, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r08-c05-copper", x: 13, y: 22, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r08-c06-copper", x: 16, y: 22, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r08-c07-copper", x: 19, y: 22, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r08-c08-copper", x: 22, y: 22, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r08-c09-copper", x: 25, y: 22, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r08-c10-copper", x: 28, y: 22, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r08-c11-copper", x: 31, y: 22, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r08-c12-copper", x: 34, y: 22, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r08-c13-copper", x: 37, y: 22, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.rightEdge },
  { id: "s2-r09-c01-copper", x: 1, y: 25, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.leftEdge },
  { id: "s2-r09-c02-copper", x: 4, y: 25, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r09-c03-copper", x: 7, y: 25, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r09-c04-copper", x: 10, y: 25, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r09-c05-copper", x: 13, y: 25, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r09-c06-copper", x: 16, y: 25, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r09-c07-copper", x: 19, y: 25, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r09-c08-copper", x: 22, y: 25, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r09-c09-copper", x: 25, y: 25, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r09-c10-copper", x: 28, y: 25, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r09-c11-copper", x: 31, y: 25, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r09-c12-copper", x: 34, y: 25, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r09-c13-copper", x: 37, y: 25, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.rightEdge },
  { id: "s2-r10-c01-copper", x: 1, y: 28, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.leftEdge },
  { id: "s2-r10-c02-copper", x: 4, y: 28, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r10-c03-copper", x: 7, y: 28, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r10-c04-copper", x: 10, y: 28, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r10-c05-copper", x: 13, y: 28, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r10-c06-copper", x: 16, y: 28, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r10-c07-copper", x: 19, y: 28, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r10-c08-copper", x: 22, y: 28, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r10-c09-copper", x: 25, y: 28, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r10-c10-copper", x: 28, y: 28, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r10-c11-copper", x: 31, y: 28, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r10-c12-copper", x: 34, y: 28, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r10-c13-copper", x: 37, y: 28, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.rightEdge },
  { id: "s2-r11-c01-copper", x: 1, y: 31, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.leftEdge },
  { id: "s2-r11-c02-copper", x: 4, y: 31, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r11-c03-copper", x: 7, y: 31, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r11-c04-copper", x: 10, y: 31, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r11-c05-copper", x: 13, y: 31, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r11-c06-copper", x: 16, y: 31, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r11-c07-copper", x: 19, y: 31, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r11-c08-copper", x: 22, y: 31, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r11-c09-copper", x: 25, y: 31, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r11-c10-copper", x: 28, y: 31, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r11-c11-copper", x: 31, y: 31, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r11-c12-copper", x: 34, y: 31, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r11-c13-copper", x: 37, y: 31, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.rightEdge },
  { id: "s2-r12-c01-copper", x: 1, y: 34, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.leftEdge },
  { id: "s2-r12-c02-copper", x: 4, y: 34, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r12-c03-copper", x: 7, y: 34, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r12-c04-copper", x: 10, y: 34, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r12-c05-copper", x: 13, y: 34, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r12-c06-copper", x: 16, y: 34, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r12-c07-copper", x: 19, y: 34, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r12-c08-copper", x: 22, y: 34, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r12-c09-copper", x: 25, y: 34, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r12-c10-copper", x: 28, y: 34, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r12-c11-copper", x: 31, y: 34, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r12-c12-copper", x: 34, y: 34, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.middleTile },
  { id: "s2-r12-c13-copper", x: 37, y: 34, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.rightEdge },
  { id: "s2-r13-c01-copper", x: 1, y: 37, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.bottomLeftCorner },
  { id: "s2-r13-c02-copper", x: 4, y: 37, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.bottomEdge },
  { id: "s2-r13-c03-copper", x: 7, y: 37, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.bottomEdge },
  { id: "s2-r13-c04-copper", x: 10, y: 37, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.bottomEdge },
  { id: "s2-r13-c05-copper", x: 13, y: 37, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.bottomEdge },
  { id: "s2-r13-c06-copper", x: 16, y: 37, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.bottomEdge },
  { id: "s2-r13-c07-copper", x: 19, y: 37, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.bottomEdge },
  { id: "s2-r13-c08-copper", x: 22, y: 37, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.bottomEdge },
  { id: "s2-r13-c09-copper", x: 25, y: 37, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.bottomEdge },
  { id: "s2-r13-c10-copper", x: 28, y: 37, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.bottomEdge },
  { id: "s2-r13-c11-copper", x: 31, y: 37, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.bottomEdge },
  { id: "s2-r13-c12-copper", x: 34, y: 37, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.bottomEdge },
  { id: "s2-r13-c13-copper", x: 37, y: 37, width: 3, height: 3, kind: "copperMine", level: 1, label: "Copper Mine", shape: copperMineShapes.bottomRightCorner },
  { id: "s2-r01-c01-town", x: 3, y: 3, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r01-c02-town", x: 6, y: 3, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r01-c03-town", x: 9, y: 3, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r01-c04-town", x: 12, y: 3, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r01-c05-town", x: 15, y: 3, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r01-c06-town", x: 18, y: 3, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r01-c07-town", x: 21, y: 3, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r01-c08-town", x: 24, y: 3, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r01-c09-town", x: 27, y: 3, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r01-c10-town", x: 30, y: 3, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r01-c11-town", x: 33, y: 3, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r01-c12-town", x: 36, y: 3, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r02-c01-town", x: 3, y: 6, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r02-c02-town", x: 6, y: 6, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r02-c03-town", x: 9, y: 6, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r02-c04-town", x: 12, y: 6, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r02-c05-town", x: 15, y: 6, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r02-c06-town", x: 18, y: 6, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r02-c07-town", x: 21, y: 6, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r02-c08-town", x: 24, y: 6, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r02-c09-town", x: 27, y: 6, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r02-c10-town", x: 30, y: 6, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r02-c11-town", x: 33, y: 6, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r02-c12-town", x: 36, y: 6, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r03-c01-town", x: 3, y: 9, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r03-c02-town", x: 6, y: 9, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r03-c03-town", x: 9, y: 9, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r03-c04-town", x: 12, y: 9, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r03-c05-town", x: 15, y: 9, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r03-c06-town", x: 18, y: 9, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r03-c07-town", x: 21, y: 9, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r03-c08-town", x: 24, y: 9, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r03-c09-town", x: 27, y: 9, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r03-c10-town", x: 30, y: 9, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r03-c11-town", x: 33, y: 9, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r03-c12-town", x: 36, y: 9, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r04-c01-town", x: 3, y: 12, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r04-c02-town", x: 6, y: 12, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r04-c03-town", x: 9, y: 12, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r04-c04-town", x: 12, y: 12, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r04-c05-town", x: 15, y: 12, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r04-c06-town", x: 18, y: 12, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r04-c07-town", x: 21, y: 12, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r04-c08-town", x: 24, y: 12, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r04-c09-town", x: 27, y: 12, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r04-c10-town", x: 30, y: 12, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r04-c11-town", x: 33, y: 12, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r04-c12-town", x: 36, y: 12, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r05-c01-town", x: 3, y: 15, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r05-c02-town", x: 6, y: 15, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r05-c03-town", x: 9, y: 15, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r05-c04-town", x: 12, y: 15, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r05-c05-town", x: 15, y: 15, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r05-c06-town", x: 18, y: 15, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r05-c07-town", x: 21, y: 15, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r05-c08-town", x: 24, y: 15, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r05-c09-town", x: 27, y: 15, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r05-c10-town", x: 30, y: 15, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r05-c11-town", x: 33, y: 15, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r05-c12-town", x: 36, y: 15, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r06-c01-town", x: 3, y: 18, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r06-c02-town", x: 6, y: 18, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r06-c03-town", x: 9, y: 18, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r06-c04-town", x: 12, y: 18, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r06-c05-town", x: 15, y: 18, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r06-c06-town", x: 18, y: 18, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r06-c07-town", x: 21, y: 18, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r06-c08-town", x: 24, y: 18, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r06-c09-town", x: 27, y: 18, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r06-c10-town", x: 30, y: 18, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r06-c11-town", x: 33, y: 18, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r06-c12-town", x: 36, y: 18, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r07-c01-town", x: 3, y: 21, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r07-c02-town", x: 6, y: 21, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r07-c03-town", x: 9, y: 21, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r07-c04-town", x: 12, y: 21, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r07-c05-town", x: 15, y: 21, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r07-c06-town", x: 18, y: 21, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r07-c07-town", x: 21, y: 21, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r07-c08-town", x: 24, y: 21, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r07-c09-town", x: 27, y: 21, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r07-c10-town", x: 30, y: 21, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r07-c11-town", x: 33, y: 21, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r07-c12-town", x: 36, y: 21, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r08-c01-town", x: 3, y: 24, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r08-c02-town", x: 6, y: 24, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r08-c03-town", x: 9, y: 24, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r08-c04-town", x: 12, y: 24, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r08-c05-town", x: 15, y: 24, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r08-c06-town", x: 18, y: 24, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r08-c07-town", x: 21, y: 24, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r08-c08-town", x: 24, y: 24, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r08-c09-town", x: 27, y: 24, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r08-c10-town", x: 30, y: 24, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r08-c11-town", x: 33, y: 24, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r08-c12-town", x: 36, y: 24, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r09-c01-town", x: 3, y: 27, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r09-c02-town", x: 6, y: 27, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r09-c03-town", x: 9, y: 27, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r09-c04-town", x: 12, y: 27, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r09-c05-town", x: 15, y: 27, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r09-c06-town", x: 18, y: 27, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r09-c07-town", x: 21, y: 27, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r09-c08-town", x: 24, y: 27, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r09-c09-town", x: 27, y: 27, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r09-c10-town", x: 30, y: 27, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r09-c11-town", x: 33, y: 27, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r09-c12-town", x: 36, y: 27, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r10-c01-town", x: 3, y: 30, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r10-c02-town", x: 6, y: 30, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r10-c03-town", x: 9, y: 30, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r10-c04-town", x: 12, y: 30, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r10-c05-town", x: 15, y: 30, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r10-c06-town", x: 18, y: 30, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r10-c07-town", x: 21, y: 30, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r10-c08-town", x: 24, y: 30, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r10-c09-town", x: 27, y: 30, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r10-c10-town", x: 30, y: 30, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r10-c11-town", x: 33, y: 30, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r10-c12-town", x: 36, y: 30, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r11-c01-town", x: 3, y: 33, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r11-c02-town", x: 6, y: 33, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r11-c03-town", x: 9, y: 33, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r11-c04-town", x: 12, y: 33, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r11-c05-town", x: 15, y: 33, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r11-c06-town", x: 18, y: 33, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r11-c07-town", x: 21, y: 33, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r11-c08-town", x: 24, y: 33, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r11-c09-town", x: 27, y: 33, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r11-c10-town", x: 30, y: 33, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r11-c11-town", x: 33, y: 33, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r11-c12-town", x: 36, y: 33, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r12-c01-town", x: 3, y: 36, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r12-c02-town", x: 6, y: 36, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r12-c03-town", x: 9, y: 36, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r12-c04-town", x: 12, y: 36, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r12-c05-town", x: 15, y: 36, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r12-c06-town", x: 18, y: 36, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r12-c07-town", x: 21, y: 36, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r12-c08-town", x: 24, y: 36, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r12-c09-town", x: 27, y: 36, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r12-c10-town", x: 30, y: 36, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r12-c11-town", x: 33, y: 36, width: 2, height: 2, kind: "town", level: 1 },
  { id: "s2-r12-c12-town", x: 36, y: 36, width: 2, height: 2, kind: "town", level: 1 },
];
